[package]
name = "cli_basics"
version = "0.1.0"
authors = ["Kirill Pimenov <kirill@pimenov.cc>"]

[dependencies]
clap = "1.4"

log = "0.3"
flexi_logger = "0.3"

hyper = "0.6"

rustc-serialize = "0.3"
